#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlrcxixjMKV4I9c4dlhddYipV9mMbCkA4UM/oQbo/JG1fhnNdNxQWN0WB2UEAXaepPPJpFh5Do2P4YApjSRSN9J5pCktF+bHh3lb5t5n8GuvRzSfmBBAoBY6efyWU+86TF/7OwtQz0ADDK56VoTW9/N5iTlbGcKSQk5XmPDkRInzbPmj9/0a4yP/km4ytu5viueCT3rEOfcogWZdc6TYqc+zznYWT5PpEU6DUIQxiu5oyH5ToHICnwxehfyFv5qXauH1Z6+CQ4hFRgJFPUO2DjG8E8qiTziEN8jP6GjucMBpi2hYADlHHAIQkDOfku/ulvifQfc0qS5/4ghL/0/08l jcallen@silicon.virtomation.com
rancher:
    services: 
        alpine-ansible-ssh:
            image: jcpowermac/alpine-ansible-ssh 
            ports:
                - 2222:22
            restart: always
            volumes:
                - projects:/home/ansible/projects
        alpine-butterfly:
            image: jcpowermac/alpine-butterfly 
            ports:
                - 57575:57575  
            restart: always
            volumes:
                - projects:/home/ansible/projects
